dist: trusty
language: python

sudo: false
matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
        - python: 3.8
          env: TOXENV=py38
          dist: xenial
          sudo: true
        - python: nightly
          env: TOXENV=py38
          dist: xenial
          sudo: true
    allow_failures:
        - python: nightly
          env: TOXENV=py38
          dist: xenial
          sudo: true

install:
    - travis_retry pip install tox

script:
    - tox
    - openssl aes-256-cbc -K $encrypted_b635b01d8012_key -iv $encrypted_b635b01d8012_iv -in dh_tgb.enc -out dh_tgb -d
    - ./travis-cron.sh
