version: "3.3"
services:
  httpbin:
    image: httpbin:latest
    build:
      context: .
      dockerfile: ./Dockerfile
  httpbin-alpine:
    image: httpbin:alpine
    build:
      context: .
      dockerfile: ./Dockerfile.alpine
  httpbin-nginx:
    image: httpbin:nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
  httpbin-unit:
    image: httpbin:unit
    build:
      context: .
      dockerfile: ./Dockerfile.unit
  httpbin-httpd:
    image: httpbin:httpd
    build:
      context: .
      dockerfile: ./Dockerfile.httpd
  httpbin-httpd-alpine:
    image: httpbin:httpd-alpine
    build:
      context: .
      dockerfile: ./Dockerfile.httpd-alpine
